version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # React app runs on port 80 inside container, but map to 3000
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Expose API on port 5000
    depends_on:
      - client
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
