name: Build, Push & Deploy to Kubernetes

on:
  # push:
    # branches:
      # - main  # Change this to the branch you want to trigger the workflow on
  pull_request:
    branches:
      - main

jobs:
  # Build and push Docker image to DockerHub
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t abhik0/discussion-forum:client_latest ./client
          docker build -t abhik0/discussion-forum:server_latest ./server
          docker push abhik0/discussion-forum:client_latest
          docker push abhik0/discussion-forum:server_latest

  # Set up EKS, apply the Kubernetes manifests
  deploy_to_eks:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2  # Change to your AWS region

      - name: Set up kubeconfig
        run: |
          aws eks --region us-west-2 update-kubeconfig --name mern-cluster

      - name: Verify kubectl is working
        run: kubectl version

      - name: Apply Kubernetes Manifests (client and server)
        run: |
          kubectl apply -f k8s/client-deployment.yml
          kubectl apply -f k8s/server-deployment.yml

      - name: Verify Kubernetes pods
        run: kubectl get pods
